<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="category-listing <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <div class="listing-products">
	        <ul class="list products-<?= /* @escapeNotVerified */ $viewMode ?>">
	            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
	            <?php foreach ($_productCollection as $_product): ?>
	                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item last">' : '</li><li class="item last">' ?>
	                <div class="product-wrapper" data-container="product-grid">
	                    <?php
	                    $productImage = $block->getImage($_product, $image);
	                    if ($pos != null) {
	                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
	                            . 'top:' . $productImage->getHeight() . 'px;"';
	                    }
	                    ?>
	                    <?php // Product Image ?>
	                    <div class="img-view">
		                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product-image" tabindex="-1">
		                        <?= $productImage->toHtml() ?>
		                    </a>
		                    <div class="actions btn-grid">
								<a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="btn small-btn">View Details</a>
							</div>
	                    </div>
	                    <div class="product-info e-height-element">
	                        <?php
	                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
	                        ?>
	                        <h2 class="product-name">
	                            <a class="product-item-link"
	                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
	                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
	                            </a>
	                        </h2>
	                        <div class="product-left" >
								<div class="product-reviews-summary">
									<div class="rating-summary">
										<span class="label"><span>Rating:</span></span>
										<div class="rating-result" title="%">
											<span style="width:0%"></span>
										</div> 
									</div>
								</div>
								<div class="price-box">
									<?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
								</div>
							</div>
							
	                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
	                        
	                        <?= $block->getProductDetailsHtml($_product) ?>

	                        <div class="add-to-links">
	                            <div class="product product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
	                                <div class="actions-primary cart"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
	                                    <?php if ($_product->isSaleable()): ?>
	                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
	                                        <form data-role="tocart-form" data-product-sku="<?=  /* @NoEscape */ $_product->getSku() ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
	                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
	                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
	                                            <?= $block->getBlockHtml('formkey') ?>
	                                            <button type="submit"
	                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
	                                                    class="whisit-bg-style link-cart btn-add-to-cart">
	                                            </button>
	                                        </form>
	                                    <?php else: ?>
	                                        <?php if ($_product->isAvailable()): ?>
	                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
	                                        <?php else: ?>
	                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
	                                        <?php endif; ?>
	                                    <?php endif; ?>
	                                </div>
	                                <div data-role="add-to-links" class="actions-secondary wishlist"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
	                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
	                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
	                                    <?php endif; ?>
	                                </div>
	                            </div>
	                            <?php if ($showDescription):?>
	                                <div class="product description product-item-description">
	                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
	                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
	                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
	                                </div>
	                            <?php endif; ?>
	                        </div>
	                    </div>
	                </div>
	                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
	            <?php endforeach; ?>
	        </ul>
        </div>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
