<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml')):?>
	<?php $layout = $block->getLayout(); ?>
    <div class="product info detailed product-info">
	    <div class="wrap clr">
	        <div class="product data items info-block info-tabs" data-mage-init='{"tabs":{"openedState":"active"}}'>
		        <div class="info-block-title clr">
			        <ul>
			            <?php foreach ($detailedInfoGroup as $name):?>
			            	<?php 
			            		$html = $layout->renderElement($name);
			            		if (!trim($html)) {
			                        continue;
			                    }
			                    $alias = $layout->getElementAlias($name);
			                    $label = $block->getChildData($alias, 'title');
			            	?>
			                <li class="data item title"
			                     aria-labeledby="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title"
			                     data-role="collapsible" id="tab-label-<?= /* @escapeNotVerified */ $alias ?>">
			                    <a class="data switch"
			                       tabindex="-1"
			                       data-toggle="switch"
			                       href="#<?= /* @escapeNotVerified */ $alias ?>"
			                       id="tab-label-<?= /* @escapeNotVerified */ $alias ?>-title">
			                        <?= /* @escapeNotVerified */ $label ?>
			                    </a>
			                </li>
			            <?php endforeach;?>
		            </ul>
	            </div>
	            <?php foreach ($detailedInfoGroup as $name):?>
	            	<?php 
	            		$html = $layout->renderElement($name);
	            		if (!trim($html)) {
	                        continue;
	                    }
	                    $alias = $layout->getElementAlias($name);
	                    $label = $block->getChildData($alias, 'title');
	            	?>
	                <div class="data item content detail-tab" id="<?= /* @escapeNotVerified */ $alias ?>" data-role="content">
	                    <?= /* @escapeNotVerified */ $html ?>
	                </div>
	            <?php endforeach;?>
	        </div>
	    </div>
    </div>
<?php endif; ?>

<?php 
		// call attribute spec_attr in backend M2
	// echo $block->getProduct()->getResource()->getAttribute('spec_attr')->getFrontend()->getValue($block->getProduct());
?>