<?php 
	namespace HelloWorld\Echo\Block;

	/**
	* 
	*/
	class Weather extends \Magento\Framework\View\Element\Template
	{
		
		protected function _prepareLayout()
        {
            return parent::_prepareLayout(); // TODO: Change the autogenerated stub
        }

    }

 ?>