<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="banner-img  shop-bg bg-img">
	<div class="page-title">
		<div id="breadcrumbs" class="breadcrumbs clr">
		    <ul class="items">
		        <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
		            <li class="item <?= /* @escapeNotVerified */ $crumbName ?>">
		            <?php if ($crumbInfo['link']) : ?>
		                <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>" title="<?= $block->escapeHtml($crumbInfo['title']) ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
		            <?php elseif ($crumbInfo['last']) : ?>
		                <strong><?= $block->escapeHtml($crumbInfo['label']) ?></strong>
		            <?php else: ?>
		                <?= $block->escapeHtml($crumbInfo['label']) ?>
		            <?php endif; ?>
		            </li>
		        <?php endforeach; ?>
		    </ul>
		</div>
		<h2 class="heading-h2 white-text"><?= $block->escapeHtml($crumbInfo['label']) ?></h2>
	</div>
</div>
<?php endif; ?>
