<div class="footer-bottom">
	<div class="wrap clr">
		<div class="col-sm-6 col-md-3">
			<div class="about-ft">
				<span><b>Illy </b>is officially distributed by Euraco Finefood Pte Ltd</span>
			</div>
			<div class="ft-logo">
				<img src="<?php echo $block -> getViewFileUrl('images/static/footre_logo.jpg'); ?>" alt="">
			</div>
		</div>
		<div class="col-sm-3 col-md-2">
			<div class="about-ft quick-links">
				<h5 class="heading-h5">Quick Links</h5>
				<ul class="page-link">
					<li><a href="<?php echo $this -> getUrl('about-us.html'); ?>">About Us</a></li>
					<li><a href="<?php echo $this -> getUrl('contact-us'); ?>">Contact Us</a></li>
					<li><a href="<?php echo $this -> getUrl('terms-conditions'); ?>">Terms &amp; Conditions</a></li>
					<li><a href="<?php echo $this -> getUrl('privacy-policy'); ?>">Privacy Policy</a></li>
				</ul>
			</div>
		</div>
		<div class="col-sm-3 col-md-2">
			<div class="about-ft">
				<h5 class="heading-h5">Follow Us</h5>
				<ul class="social-media">
					<li class="facebook-icon"><i class="fa fa-facebook" aria-hidden="true"></i><a href="https://www.facebook.com/sang.soanseo">Facebook</a></li>
					<li class="instagram-icon"><i class="fa fa-instagram" aria-hidden="true"></i><a href="https://www.instagram.com/unitymta/">Instagram</a></li>
				</ul>
			</div>
		</div>
		<div class="col-sm-12 col-md-5 on-position">
			<div class="cards">
				<span>Copyright © 2017 Euraco Finefood Pte Ltd. All rights reserved.</span>
				<ul>
					<li><a href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/static/card_amirican.png');?>" alt=""></a></li>
					<li><a href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/static/card_paypal.png');?>" alt=""></a></li>
					<li><a href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/static/card_visa.png');?>" alt=""></a></li>
					<li><a href="javascript:void(0)"><img src="<?php echo $block->getViewFileUrl('images/static/card_blue.png');?>" alt=""></a></li>
				</ul>
			</div>
		</div>
	</div>
</div>