<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;

            $image = 'related_products_list';
            $title = __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

            $image = 'upsell_products_list';
            $title = __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = true;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('More Choices:');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = count($block->getItems())) {
            $type = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $title = __('Frequently Bought Together');
            $items = $block->getItems();

            $shuffle = 0;
            $limit = 0;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

            $class = 'widget' . ' ' . $type;

            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'crosssell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="space-div related-products <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php else: ?>
            <div class="space-div bought-together <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?= /* @escapeNotVerified */ $class ?>">
    <?php endif; ?>
    <div class="wrap clr">
	    <div class="page-title center">
	        <h2 class="heading-h2" id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></h2>
	    </div>
	    <div class="category-products" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
	        <div class="<?= /* @escapeNotVerified */ $type ?>">
	            <ul class="products-grid products-grid--max-4-col e-height-cnt">
		            <div class="regular slider">
		                <?php $iterator = 1; ?>
		                <?php foreach ($items as $_item): ?>
		                <?php $available = ''; ?>
		                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
		                    <?php if (!$_item->getRequiredOptions()): ?>
		                        <?php $available = 'related-available'; ?>
		                    <?php endif; ?>
		                <?php endif; ?>
		                <?php if ($type == 'related' || $type == 'crosssell'): ?>
		                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item last">' : '</li><li class="item last">' ?>
		                <?php else: ?>
		                    <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item last">' : '</li><li class="item last">' ?>
		                <?php endif; ?>
		                <div class="product-wrapper <?= /* @escapeNotVerified */ $available ?>">
		                	<div class="product-label">
		                		<?php
                                    $price = $_item->getPrice();
                                    $finalPrice = $_item->getFinalPrice();
                                ?>
                                <?php if($finalPrice < $price): ?>
									<span class="sale-product-icon round-bg-style">Sale</span>
								<?php endif; ?>
							</div>
							<div class="img-view">
			                    <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
			                    <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>" class="product-image">
			                        <?= $block->getImage($_item, $image)->toHtml() ?>
			                    </a>
			                    <div class="actions btn-grid">
									<a href"#" class="btn small-btn">View Details</a>
								</div>
		                    </div>
		                    <div class="product-info e-height-element">
		                        <h2 class="product-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
		                            <?= $block->escapeHtml($_item->getName()) ?>
		                            <span class="category-icon"></span></a>
		                        </h2>
								<div class="product-left">
									<div class="product-reviews-summary">
										<div class="rating-summary">
											<span class="label"><span>Rating:</span></span>
											<div class="rating-result" title="%">
												<span style="width:0%"></span>
											</div> 
										</div>
									</div>

									<?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>
								</div>

		                            <?php if ($templateType): ?>
		                                <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
		                            <?php endif; ?>

		                            <?php if ($showAddTo || $showCart): ?>
		                                <ul class="add-to-links">
		                                    <?php if ($showCart): ?>
	                                            <?php if ($_item->isSaleable()): ?>
	                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
	                                                	<li class="cart">
		                                                    <button class="whisit-bg-style link-cart btn-add-to-cart" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
		                                                    </button>
	                                                    </li>
	                                                    <li class="wishlist"><a href="#" class="whisit-bg-style link-wishlist"></a></li>
	                                                <?php else: ?>
	                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
	                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
	                                                    ?>
	                                                    <li class="cart">
		                                                    <button class="whisit-bg-style link-cart btn-add-to-cart"
	                                                            data-post='<?= /* @escapeNotVerified */ $postData ?>'
	                                                            type="button" title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
		                                                    </button>
	                                                    </li>
	                                                    <li class="wishlist"><a href="#" class="whisit-bg-style link-wishlist"></a></li>
	                                                <?php endif; ?>
	                                            <?php else: ?>
	                                                <?php if ($_item->getIsSalable()): ?>
	                                                    <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
	                                                <?php else: ?>
	                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
	                                                <?php endif; ?>
	                                            <?php endif; ?>
		                                    <?php endif; ?>

		                                    <?php if ($showAddTo): ?>
		                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
		                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
		                                                <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
		                                            <?php endif; ?>
		                                        </div>
		                                    <?php endif; ?>
		                                </ul>
		                            <?php endif; ?>
		                    </div>
		                </div>
		                    <?= ($iterator == count($items)+1) ? '</li>' : '' ?>
		                <?php endforeach ?>
		            </div>
	            </ul>
	        </div>
	    </div>
    </div>
</div>
<?php endif;?>
