<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="newsletter">
    <h4>Subscribe to Our Mailing List</h4>
    <form class="form"
        novalidate
        action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
        method="post"
        data-mage-init='{"validation": {"errorClass": "mage-error"}}'
        id="newsletter-validate-detail">
        <div class="input-wrap">
            <input name="email" type="email" id="newsletter"
                        placeholder="<?= $block->escapeHtmlAttr(__('Enter E-mail Address')) ?>"
                        data-validate="{required:true, 'validate-email':true}"/>
             <button class="btn" title="<?= $block->escapeHtmlAttr(__('Go')) ?>" type="submit">
                <span><?= $block->escapeHtml(__('Go')) ?></span>
            </button>
        </div>
    </form>
</div>
