<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<div id="amasty-shopby-product-list">
	<?php if (!$block->isContentMode() || $block->isMixedMode()): ?>
	    <?= $block->getProductListHtml() ?>
	<?php endif; ?>
</div>