<?php
use Magento\Framework\App\Action\Action;

?>
<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    /** @var \Magento\Catalog\Model\ResourceModel\Product\Collection $productCollection */
    $_productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\Collection');
    /** Apply filters here */
    $_productCollection->addAttributeToSelect('*');
    $_productCollection->addCategoriesFilter(['in' => [3]]);
    $_productCollection->setPageSize(1);
    $_productCollection->load();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $pos = $block->getPositioned();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<?php if ($_productCollection->count()): ?>
<?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
<div class="feature bg-img space-div">
    <div class="wrap clr">
        <div class="monthly-feature">
            <div class="block-content">
                <!-- new_products_content_widget_grid-->            
                <div class="products-grid grid">
                    <ol class="product-items widget-product-grid">
                        <?php foreach ($_productCollection as $_product): ?>
                        <li class="product-item">
                            <div class="product-item-info">
                            	<div class="product-item-details">
                                	<strong>Monthly Feature</strong>
                                    <h2 class="heading-h2">
                                        <?php
                                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                        ?>
                                        <a title="<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-link"><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                    </h2>

                                    <?php 
                                    	if ($showDescription) {
					                        echo $description =  '<div class="description">'
					                                                . $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')
					                                                . '</div>';
					                    } else {
					                        $description = '';
					                    }
                                     ?>

                                    <div class="price-box" data-role="priceBox" data-product-id="<?php echo $_product->getId(); ?>">
                                        <span class="regular-price">
                                            <?php
                                            //print_r();exit;
                                            //$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                            $currencysymbol = 'S$';
                                            $msrp = $_product->getMsrp();
                                            $price = $_product->getPrice();
                                            $finalPrice = $_product->getFinalPrice();
                                            $save = 0; 
                                            if($finalPrice < $price){
                                                $save = 100 - ($finalPrice/$price) * 100;
                                            }elseif($finalPrice < $msrp){
                                                $save = 100 - ($finalPrice/$msrp) * 100;
                                            }
                                            $save = number_format($save, 0);
                                            ?>
                                            <?php if($finalPrice < $price): ?>
                                            <span  id="old-price-6-widget-product-grid" data-price-amount="<?php echo $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper " >
                                                <span class="price <?php if($finalPrice == $price) echo 'price-new'; ?>"><?php echo $currencysymbol .number_format($finalPrice,2); ?></span>
                                                <span class="price-was">was <?php echo $currencysymbol .number_format($price, 2); ?></span>
                                            </span>
                                            <span data-price-amount="<?php echo $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper ">
                                                <span class="price-mrsp"><?php if($msrp) echo 'mrsp '.$currencysymbol .number_format($msrp, 2); ?></span>
                                                <span class="price-save">save <?php echo $save; ?>%</span>
                                            </span>
                                            <?php elseif($finalPrice < $msrp): ?>
                                            <span  id="old-price-6-widget-product-grid" data-price-amount="<?php echo $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper " >
                                                <span class="price <?php if($finalPrice == $price) echo 'price-new'; ?>"><?php echo $currencysymbol .number_format($finalPrice,2); ?></span>
                                                
                                            </span>
                                            <span data-price-amount="<?php echo $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper ">
                                                <span class="price-mrsp"><?php if($msrp) echo 'mrsp '.$currencysymbol .number_format($msrp, 2); ?></span>
                                                <span class="price-save">save <?php echo $save; ?>%</span>
                                            </span>
                                            <?php else: ?>
                                            <span  id="old-price-6-widget-product-grid" data-price-amount="<?php echo $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper " >
                                                <span class="price price-new"><?php echo $currencysymbol .number_format($finalPrice,2); ?></span>
                                            </span>
                                            <?php endif; ?>
                                        </span>
                                    </div>
                                    
                                    <div class="btn-grid">
                                        <div class="actions-primary">
                                            <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" 
                                            	action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">

                                                <?php echo $block->getBlockHtml('formkey')?>

                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="btn btn-black small-btn action tocart primary btn-add-to-cart">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                                
                                                <a class="btn btn-red small-btn" title="<?php echo $block->escapeHtml(__('More Details')); ?>" href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" ><span><?php /* @escapeNotVerified */ echo __('More Details') ?></span>
                                                </a>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->getIsSalable()): ?>
                                                <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <button title="Stock Coming Soon" type="button" class="action tocart primary coming-soon">
																	<span>Stock Coming Soon</span>
																</button>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                        </div>
                                    </div>
                                    <?php if($_product->getFreeshipping()): ?>
                                    <div class="box-free-shipping"><span>Free <strong>shipping</strong></span>></div>
                                    <?php endif; ?>
                                </div>
                                
                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product-item-photo">
                                    <span class="product-image-container">
                                        <span class="product-image-wrapper">
                                            <?php
                                                // $image = 'category_page_grid';
                                                // $productImage = $block->getImage($_product, $image);
                                                // if ($pos != null) {
                                                //     $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                                //         . 'top:' . $productImage->getHeight() . 'px;"';
                                                // }
                                            	$productImageUrl = $block->getUrl('pub/media/catalog').'product'.$_product->getImage();
                                            ?>
											<img src="<?= $productImageUrl; ?>" />
                                        </span>
                                    </span>
                                </a>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- END feature -->
<?php endif; ?>