<div class="wrap clr">
	<div class="solution-inner">
		<div class="col-sm-6 col-md-6 col-xs-12">
			<div class="solution cta-one bg-solution">
				<h4 class="heading-h4"> Professional <span> Solution </span></h4>
				<p>Praesent sapien massa, convallis a <br> pellentesque nec egestas non.</p>
				<div class="read-btn">
					<a href="#" class="learn-more">Learn More</a>
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-6 col-xs-12">
			<div class="solution cta-two bg-solution">
				<h4 class="heading-h4">Corporate <span> Solution </span></h4>
				<p>Praesent sapien massa, convallis a <br> pellentesque nec egestas non.</p>
				<div class="read-btn">
					<a href="#" class="learn-more">Learn More</a>
				</div>
			</div>
		</div>
	</div>
</div>